#!/usr/bin/env bash

set -e

echo "---> Installing application source"
cp -Rf /tmp/src/. ./

if [ -f ./nginx.conf ]; then
  echo "---> Copying nginx.conf configuration file..."
  rm -rf NGINX_CONFIGURATION_PATH/*
  mv -f ./nginx.conf "${NGINX_CONF_PATH}"
fi

echo "---> Fix permissions"
chown -R 1001:0 $APP_ROOT
find $APP_ROOT -type d -exec chmod 555 {} +
find $APP_ROOT -type f -exec chmod 444 {} +
chown -R 1001:0 /etc/nginx
find /etc/nginx -type d -exec chmod 555 {} +
find /etc/nginx -type f -exec chmod 444 {} +
