#!/usr/bin/env sh

cat <<EOF
This is a S2I builder image for static web applications wanting to use nginx.

If you wish to customize nginx, place an nginx.conf file at the root of your source repository.

Sample invocation:
s2i build --copy . nccurry/nginx-s2i-builder:latest sample-app

You can then run the resulting image via:
docker run -p 8080:8080 sample-app
EOF
